### ISSUE TITLE
make sure no temporary files are left by SS client and connectors

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStream#32]
- [ ] make sure client deletes tmp files it creates https://github.com/slipstream/SlipStreamClient/issues/68
- [x] StratusLab connector leaves /tmp/stratuslab_*.{err,log} files https://github.com/slipstream/SlipStreamConnectors/issues/12
- [ ] vCloud postcustomization script https://github.com/SixSq/SlipStreamConnector-vCloud/issues/6
